
server:
  port: 8761
  
spring:
  application:
    name: eureka-service
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
  server:
    enable-self-preservation: false 
    eviction-interval-timer-in-ms: 1000 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
      
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
